### ISSUE TITLE
Wrong accessibility?

### ISSUE THREAD

**Issue by gr1-pro** [peterwurzinger/AuthOida#6]
Using the most recent package in a NET 6 MVC app fails in
`        builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                  .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"))
                  .AddMappedGroups();
`
due to not being able to find a matching constructor.

After changing class and method definitions in GroupsMapper and GroupsMapOptainer from internal to public, the application can start.
However the Graph call(s) fails with 'ServiceException: Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation.' (this may be an issue related to app registration)

**Comment by peterwurzinger** [comment]
Thanks for reaching out.

Indeed, yes. I didn't want to invest time to test the versions starting with .NET 6 against a real life Azure AD, because I haven't had the need using this library myself anymore, and I wans't aware of that somebody is actively using it. So it became more like a showcase of new .NET or C# versions.

That issue is fixed in version 1.26, alongside some dependency updates:
https://github.com/peterwurzinger/AuthOida/pkgs/nuget/AuthOida.Microsoft.Identity.Groups/76618506
If you could try that and confirm it to be working, I would then release it.

The second error you mentioned is most likely related to a app registration missing permissions, yes.

**Comment by gr1-pro** [comment]
Thank you for very fast reaction

 

Unfortunately I’m not able to install the preview version:

 

<Project folder>dotnet add package AuthOida.Microsoft.Identity.Groups --version 1.26.0-preview.86

  Determining projects to restore...

  Writing C:\Users\PRO\AppData\Local\Temp\tmp1301.tmp

info : X.509 certificate chain validation will use the default trust store selected by .NET.

info : X.509 certificate chain validation will use the default trust store selected by .NET.

info : Adding PackageReference for package 'AuthOida.Microsoft.Identity.Groups' into project 'F:\Repos\GDPR\GR1.GDPR.WebSites\GR1.GDPR.WebSites.csproj'.

info : Restoring packages for F:\Repos\GDPR\GR1.GDPR.WebSites\GR1.GDPR.WebSites.csproj...

info :   CACHE https://api.nuget.org/v3-flatcontainer/authoida.microsoft.identity.groups/index.json

error: NU1102: Unable to find package AuthOida.Microsoft.Identity.Groups with version (>= 1.26.0-preview.86)

error:   - Found 10 version(s) in nuget.org [ Nearest version: 1.25.3 ]

error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

error:   - Found 0 version(s) in Local packages

error: Package 'AuthOida.Microsoft.Identity.Groups' is incompatible with 'all' frameworks in project '<Project folder>\<project>.csproj'.

 

Med venlig hilsen / Best regards

 

Peter Rosenkilde Roed

GR-1

**Comment by peterwurzinger** [comment]
Hi @gr1-pro,
just wanted to check in if you had the time to test the prerelease packages, and if I can release them into the wild as stable packages?

Cheers

**Comment by gr1-pro** [comment]
Hello

 

I answered on 13/3 but it seems that you did not get my reply:

 

Thank you for very fast reaction

 

Unfortunately I’m not able to install the preview version:

 

<Project folder>dotnet add package AuthOida.Microsoft.Identity.Groups --version 1.26.0-preview.86

  Determining projects to restore...

  Writing C:\Users\PRO\AppData\Local\Temp\tmp1301.tmp

info : X.509 certificate chain validation will use the default trust store selected by .NET.

info : X.509 certificate chain validation will use the default trust store selected by .NET.

info : Adding PackageReference for package 'AuthOida.Microsoft.Identity.Groups' into project 'F:\Repos\GDPR\GR1.GDPR.WebSites\GR1.GDPR.WebSites.csproj'.

info : Restoring packages for F:\Repos\GDPR\GR1.GDPR.WebSites\GR1.GDPR.WebSites.csproj...

info :   CACHE https://api.nuget.org/v3-flatcontainer/authoida.microsoft.identity.groups/index.json

error: NU1102: Unable to find package AuthOida.Microsoft.Identity.Groups with version (>= 1.26.0-preview.86)

error:   - Found 10 version(s) in nuget.org [ Nearest version: 1.25.3 ]

error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

error:   - Found 0 version(s) in Local packages

error: Package 'AuthOida.Microsoft.Identity.Groups' is incompatible with 'all' frameworks in project '<Project folder>\<project>.csproj'.

 

Med venlig hilsen / Best regards

 

Peter Rosenkilde Roed

GR-1

**Comment by peterwurzinger** [comment]
According to the error message you're seeing, I would assume, that you haven't added the Prerelease-Feed hosted on Github as NuGet source.
Please see this article for details:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-with-a-personal-access-token

**Comment by peterwurzinger** [comment]
@gr1-pro If it is still relevant to you, I just released 1.26.0, that should cover this fix.

It will likely also be the last version for the 1.x versions of Microsoft.Identity.Web
